/**
 * Generate the service worker from the actual export.
 *
 * PRD §12: "Fully offline after first load." That is a real claim, and the only
 * honest way to make it is to precache the files that actually exist rather than a
 * hand-maintained list that drifts the first time a chunk is renamed. So this runs
 * after `next build`, walks `out/`, and writes a worker whose manifest *is* the build.
 *
 * The cache name carries a hash of that manifest, so a build that changes anything
 * gets a new cache and the old one is dropped on activate. A build that changes
 * nothing reuses it, which keeps repeat deploys from evicting a working cache.
 */

import { createHash } from 'node:crypto'
import { readdir, readFile, stat, writeFile } from 'node:fs/promises'
import { join, relative, sep } from 'node:path'

const ROOT = join(process.cwd(), 'out')
const BASE_PATH = '/raft-simulator'
const SW_NAME = 'sw.js'

/** Every file in the export, as basePath-rooted URLs, sorted for a stable hash. */
async function collect(dir) {
  const found = []
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name)
    if (entry.isDirectory()) {
      found.push(...(await collect(full)))
      continue
    }
    found.push(full)
  }
  return found
}

const files = (await collect(ROOT))
  .map((full) => relative(ROOT, full).split(sep).join('/'))
  .filter((rel) => rel !== SW_NAME)
  .sort()

// Hash contents, not names: a rebuild that produces identical bytes should not
// invalidate a cache that is already correct.
const hash = createHash('sha256')
for (const rel of files) {
  hash.update(rel)
  hash.update(await readFile(join(ROOT, rel)))
}
const version = hash.digest('hex').slice(0, 12)

/**
 * What to precache. Directory index files are also registered under their directory
 * URL, because that is what the browser actually requests: `/raft-simulator/en/simulasi/`,
 * not `/mufakat/id/simulasi/index.html`.
 */
const precache = new Set()
for (const rel of files) {
  // `.nojekyll` is for Pages' build step and is never fetched by the app.
  if (rel === '.nojekyll') continue
  precache.add(`${BASE_PATH}/${rel}`)
  if (rel === 'index.html') precache.add(`${BASE_PATH}/`)
  else if (rel.endsWith('/index.html')) {
    precache.add(`${BASE_PATH}/${rel.slice(0, -'index.html'.length)}`)
  }
}

const manifest = [...precache].sort()

const worker = `/*
 * Raft Simulator service worker — generated by scripts/generate-sw.mjs. Do not edit.
 * Build ${version}, ${manifest.length} entries.
 */
const VERSION = ${JSON.stringify(version)}
const CACHE = 'raft-simulator-' + VERSION
const BASE_PATH = ${JSON.stringify(BASE_PATH)}
const PRECACHE = ${JSON.stringify(manifest, null, 2)}

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches
      .open(CACHE)
      .then((cache) => cache.addAll(PRECACHE))
      // Take over as soon as the new build is cached, rather than waiting for every
      // tab to close. The app holds no cross-version state, so there is nothing for a
      // mixed-version moment to corrupt.
      .then(() => self.skipWaiting()),
  )
})

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((key) => key !== CACHE).map((key) => caches.delete(key))))
      .then(() => self.clients.claim()),
  )
})

self.addEventListener('fetch', (event) => {
  const request = event.request
  if (request.method !== 'GET') return

  const url = new URL(request.url)
  if (url.origin !== self.location.origin) return
  if (!url.pathname.startsWith(BASE_PATH)) return

  // Hashed build assets are immutable: their name changes when their contents do, so
  // going to the network for them can only ever be slower.
  if (url.pathname.startsWith(BASE_PATH + '/_next/static/')) {
    event.respondWith(
      caches.match(request).then((hit) => hit || fetch(request).then((response) => {
        const copy = response.clone()
        caches.open(CACHE).then((cache) => cache.put(request, copy))
        return response
      })),
    )
    return
  }

  // Everything else — the HTML routes — is network-first so a deployed change is
  // picked up promptly, falling back to the cache when offline. A navigation that
  // misses entirely falls back to the site root rather than the browser's error page.
  event.respondWith(
    fetch(request)
      .then((response) => {
        const copy = response.clone()
        caches.open(CACHE).then((cache) => cache.put(request, copy))
        return response
      })
      .catch(() =>
        caches
          .match(request)
          .then((hit) => hit || (request.mode === 'navigate' ? caches.match(BASE_PATH + '/') : undefined))
          .then((hit) => hit || Response.error()),
      ),
  )
})
`

await writeFile(join(ROOT, SW_NAME), worker, 'utf8')
const bytes = (await stat(join(ROOT, SW_NAME))).size
console.log(
  `Service worker: ${manifest.length} precached entries, build ${version}, ${bytes} bytes.`,
)
